### ISSUE TITLE
Workflow Breaks After Force Pull: Metadata Corruption and Unnecessary Force Operations

### ISSUE THREAD

**Issue by bagnier** [thor314/hackmd-obsidian#6]
There are two problems disrupting the sync workflow:

1. The plugin unnecessarily requires a Force Pull after the initial Push, even when the only local changes are the frontmatter properties added by the plugin itself. This creates friction in the normal sync workflow.

2. When Force Pull is used, it corrupts the sync relationship by not preserving the `hackmd` property structure in the frontmatter. This breaks subsequent sync operations.

These issues prevent a smooth bidirectional sync workflow between Obsidian and HackMD.

## Environment
- Obsidian Version: 1.8.7
- Operating System: macOS
- HackMD Plugin Version: 1.0.3 (installed from sources)
- Installation: Manual installation from sources

## Steps to Reproduce
1. Install and enable the HackMD plugin in Obsidian
2. Import HackMD API key
3. Create new note in Obsidian with title and content
4. Execute "HackMD Sync: Push" command
5. Verify initial frontmatter structure:
   ```yaml
   ---
   hackmd:
     url: https://hackmd.io/xxxxxxxxx
     title: Untitled
     lastSync: 2025-02-20T09:29:18.181Z
   ---
   ```
6. Add content on HackMD website
7. ❌ Attempt "HackMD Sync: Pull" (fails because of the local file modification)
8. Execute "HackMD Sync: Force Pull"
9. ❌ Observe corrupted frontmatter structure:
   ```yaml
   ---
   url: https://hackmd.io/xxxxxxxxx
   title: Untitled
   lastSync: 2025-02-20T11:09:42.526Z
   ---
   ```
10. ❌ Attempt "HackMD Sync: Pull" (fails due to corrupted metadata)
11. ❌ Attempt "HackMD Sync: Push" (creates duplicate document)
12. Observe duplicated metadata:
    ```yaml
    ---
    url: https://hackmd.io/xxxxxxxxx
    title: Untitled
    lastSync: 2025-02-20T11:09:42.526Z
    hackmd:
      url: https://hackmd.io/yyyyyyyyyyy
      title: Untitled
      lastSync: 2025-02-20T11:13:26.727Z
    ---
    ```

## Expected Behavior
1. Force Pull should not be required after the first push
2. Force Pull should maintain the correct frontmatter structure under the `hackmd` namespace
3. Subsequent sync operations should reuse existing sync relationship
4. No duplicate documents should be created

## Actual Behavior
1. Force Pull corrupts frontmatter by removing `hackmd` namespace
2. Regular Pull fails due to invalid metadata structure
3. Push creates new document instead of updating existing one
4. Results in duplicate metadata in frontmatter
5. Original sync relationship is permanently broken

## Technical Cause

frontmatter corruption might come from this suspicious 'id' search in [src/main.ts](https://github.com/thor314/hackmd-obsidian/blob/f630de8e314ac98285dc6b447768d9d04c7d2a3a/src/main.ts#L235C5-L244C6)
```ts
if ('id' in metadata) {
      // It's HackMD metadata
      updatedFrontmatter.hackmd = metadata as HackMDMetadata;
    } else {
      // It's a general frontmatter update
      updatedFrontmatter = {
        ...updatedFrontmatter,
        ...metadata
      };
```
